apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
  labels:
    app: fitness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
        - name: fitness-app
          image: chali009/fitness-app:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fitness-service
spec:
  selector:
    app: fitness-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
